let idDataBuyItem = [];
let productPrice;
let productName;
let dataSort = [];
let testData;
let data;
let pushData;
let tesDataDescending;
let test = false;
let whoAddBasket = [];
let quanityProduct = 1;
let endProductArray = [];
let endPrice = 0;