window.productList = {
    id: [  
        {
            id: "1" ,
            price: "5 000 р" ,
            product: "Стул" ,
            classProduct: "chair" ,
            },
            {
            id: "2" ,
            price: "12 000 р" ,
            product: "Стол" ,
            classProduct: "table" ,
            },
            {
            id: "3" ,
            price: "6 000 р" ,
            product: "Стул" ,
            classProduct: "chair" ,
            },
            {
            id: "4" ,
            price: "12 000 р" ,
            product: "Стол" ,
            classProduct: "table" ,
            },
            {
            id: "5" ,
            price: "8 000 р" ,
            product: "Стол" ,
            classProduct: "table" ,
            },
            {
            id: "6" ,
            price: "9 000 р" ,
            product: "Стол" ,
            classProduct: "table" ,
            },
            {
            id: "7" ,
            price: "9 000 р" ,
            product: "Стол" ,
            classProduct: "table" ,
            },
            {
            id: "8" ,
            price: "5 000 р" ,
            product: "Стол" ,
            classProduct: "table" ,
            },
            {
            id: "9" ,
            price: "9 000 р" ,
            product: "Стол" ,
            classProduct: "table" ,
            },
            {
            id: "10" ,
            price: "1 000 р" ,
            product: "Стол" ,
            classProduct: "table" ,
            },
            {
            id: "11" ,
            price: "5 000 р" ,
            product: "Комплект" ,
            classProduct: "set" ,
            },
            {
            id: "12" ,
            price: "2 000 р" ,
            product: "Стол" ,
            classProduct: "table" ,
            },
            {
            id: "13" ,
            price: "4 000 р" ,
            product: "Комплект" ,
            classProduct: "set" ,
            },
            {
            id: "14" ,
            price: "9 000 р" ,
            product: "Стул" ,
            classProduct: "chair" ,
            },
            {
            id: "15" ,
            price: "9 000 р" ,
            product: "Стол" ,
            classProduct: "table" ,
            },
            {
            id: "16" ,
            price: "10 000 р" ,
            product: "Стол" ,
            classProduct: "table" ,
            },
            {
            id: "17" ,
            price: "4 000 р" ,
            product: "Стол" ,
            classProduct: "table" ,
            },
            {
            id: "18" ,
            price: "12 000 р" ,
            product: "Стул" ,
            classProduct: "chair" ,
            },
            {
            id: "19" ,
            price: "11 000 р" ,
            product: "Стол" ,
            classProduct: "table" ,
            },
            {
            id: "20" ,
            price: "11 000 р" ,
            product: "Стол" ,
            classProduct: "table" ,
            },
            {
            id: "21" ,
            price: "2 000 р" ,
            product: "Стол" ,
            classProduct: "table" ,
            },
            {
            id: "22" ,
            price: "2 000 р" ,
            product: "Стул" ,
            classProduct: "chair" ,
            },
            {
            id: "23" ,
            price: "12 000 р" ,
            product: "Комплект" ,
            classProduct: "set" ,
            },
            {
            id: "24" ,
            price: "3 000 р" ,
            product: "Комплект" ,
            classProduct: "set" ,
            },
            {
            id: "25" ,
            price: "12 000 р" ,
            product: "Стул" ,
            classProduct: "chair" ,
            },
            {
            id: "26" ,
            price: "1 000 р" ,
            product: "Стул" ,
            classProduct: "chair" ,
            },
            {
            id: "27" ,
            price: "11 000 р" ,
            product: "Стол" ,
            classProduct: "table" ,
            },
            {
            id: "28" ,
            price: "2 000 р" ,
            product: "Комплект" ,
            classProduct: "set" ,
            },
            {
            id: "29" ,
            price: "9 000 р" ,
            product: "Стул" ,
            classProduct: "chair" ,
            },
            {
            id: "30" ,
            price: "6 000 р" ,
            product: "Стул" ,
            classProduct: "chair" ,
            },
            {
            id: "31" ,
            price: "9 000 р" ,
            product: "Стул" ,
            classProduct: "chair" ,
            },
            {
            id: "32" ,
            price: "6 000 р" ,
            product: "Стол" ,
            classProduct: "table" ,
            },
            {
            id: "33" ,
            price: "11 000 р" ,
            product: "Комплект" ,
            classProduct: "set" ,
            },
            {
            id: "34" ,
            price: "7 000 р" ,
            product: "Комплект" ,
            classProduct: "set" ,
            },
            {
            id: "35" ,
            price: "6 000 р" ,
            product: "Стол" ,
            classProduct: "table" ,
            },
            {
            id: "36" ,
            price: "10 000 р" ,
            product: "Стул" ,
            classProduct: "chair" ,
            },
            {
            id: "37" ,
            price: "8 000 р" ,
            product: "Комплект" ,
            classProduct: "set" ,
            },
            {
            id: "38" ,
            price: "11 000 р" ,
            product: "Комплект" ,
            classProduct: "set" ,
            },
            {
            id: "39" ,
            price: "7 000 р" ,
            product: "Стол" ,
            classProduct: "table" ,
            },
            {
            id: "40" ,
            price: "2 000 р" ,
            product: "Стол" ,
            classProduct: "table" ,
            },
            {
            id: "41" ,
            price: "10 000 р" ,
            product: "Комплект" ,
            classProduct: "set" ,
            },
            {
            id: "42" ,
            price: "1 000 р" ,
            product: "Комплект" ,
            classProduct: "set" ,
            },
            {
            id: "43" ,
            price: "8 000 р" ,
            product: "Комплект" ,
            classProduct: "set" ,
            },
            {
            id: "44" ,
            price: "8 000 р" ,
            product: "Стул" ,
            classProduct: "chair" ,
            },
            {
            id: "45" ,
            price: "12 000 р" ,
            product: "Комплект" ,
            classProduct: "set" ,
            },
            {
            id: "46" ,
            price: "12 000 р" ,
            product: "Стол" ,
            classProduct: "table" ,
            },
            {
            id: "47" ,
            price: "2 000 р" ,
            product: "Стул" ,
            classProduct: "chair" ,
            },
            {
            id: "48" ,
            price: "6 000 р" ,
            product: "Комплект" ,
            classProduct: "set" ,
            },
            {
            id: "49" ,
            price: "10 000 р" ,
            product: "Комплект" ,
            classProduct: "set" ,
            },
            {
            id: "50" ,
            price: "4 000 р" ,
            product: "Стол" ,
            classProduct: "table" ,
            },
        ],
    };  
    
