window.productList = [
  
        {
            id: "1" ,
            price: "3000" ,
            product: "Стул" ,
            classProduct: "chair" ,
            img: "18.png" ,
            },
            {
            id: "2" ,
            price: "11000" ,
            product: "Стол" ,
            classProduct: "table" ,
            img: "1.png" ,
            },
            {
            id: "3" ,
            price: "10000" ,
            product: "Стол" ,
            classProduct: "table" ,
            img: "2.png" ,
            },
            {
            id: "4" ,
            price: "6000" ,
            product: "Стул" ,
            classProduct: "chair" ,
            img: "19.png" ,
            },
            {
            id: "5" ,
            price: "9000" ,
            product: "Комплект" ,
            classProduct: "set" ,
            img: "39.png" ,
            },
            {
            id: "6" ,
            price: "8000" ,
            product: "Стул" ,
            classProduct: "chair" ,
            img: "49.png" ,
            },
            {
            id: "7" ,
            price: "5000" ,
            product: "Стол" ,
            classProduct: "table" ,
            img: "3.png" ,
            },
            {
            id: "8" ,
            price: "9000" ,
            product: "Комплект" ,
            classProduct: "set" ,
            img: "40.png" ,
            },
            {
            id: "9" ,
            price: "9000" ,
            product: "Комплект" ,
            classProduct: "set" ,
            img: "41.png" ,
            },
            {
            id: "10" ,
            price: "7000" ,
            product: "Стул" ,
            classProduct: "chair" ,
            img: "20.png" ,
            },
            {
            id: "11" ,
            price: "12000" ,
            product: "Стул" ,
            classProduct: "chair" ,
            img: "21.png" ,
            },
            {
            id: "12" ,
            price: "6000" ,
            product: "Стол" ,
            classProduct: "table" ,
            img: "4.png" ,
            },
            {
            id: "13" ,
            price: "9000" ,
            product: "Комплект" ,
            classProduct: "set" ,
            img: "42.png" ,
            },
            {
            id: "14" ,
            price: "3000" ,
            product: "Стул" ,
            classProduct: "chair" ,
            img: "22.png" ,
            },
            {
            id: "15" ,
            price: "2000" ,
            product: "Стул" ,
            classProduct: "chair" ,
            img: "23.png" ,
            },
            {
            id: "16" ,
            price: "8000" ,
            product: "Стул" ,
            classProduct: "chair" ,
            img: "24.png" ,
            },
            {
            id: "17" ,
            price: "6000" ,
            product: "Стол" ,
            classProduct: "table" ,
            img: "5.png" ,
            },
            {
            id: "18" ,
            price: "10000" ,
            product: "Стул" ,
            classProduct: "chair" ,
            img: "25.png" ,
            },
            {
            id: "19" ,
            price: "4000" ,
            product: "Стол" ,
            classProduct: "table" ,
            img: "6.png" ,
            },
            {
            id: "20" ,
            price: "12000" ,
            product: "Стол" ,
            classProduct: "table" ,
            img: "7.png" ,
            },
            {
            id: "21" ,
            price: "4000" ,
            product: "Стол" ,
            classProduct: "table" ,
            img: "8.png" ,
            },
            {
            id: "22" ,
            price: "5000" ,
            product: "Стул" ,
            classProduct: "chair" ,
            img: "26.png" ,
            },
            {
            id: "23" ,
            price: "11000" ,
            product: "Комплект" ,
            classProduct: "set" ,
            img: "43.png" ,
            },
            {
            id: "24" ,
            price: "3000" ,
            product: "Стул" ,
            classProduct: "chair" ,
            img: "27.png" ,
            },
            {
            id: "25" ,
            price: "5000" ,
            product: "Стол" ,
            classProduct: "table" ,
            img: "9.png" ,
            },
            {
            id: "26" ,
            price: "5000" ,
            product: "Стул" ,
            classProduct: "chair" ,
            img: "28.png" ,
            },
            {
            id: "27" ,
            price: "10000" ,
            product: "Стол" ,
            classProduct: "table" ,
            img: "10.png" ,
            },
            {
            id: "28" ,
            price: "3000" ,
            product: "Стул" ,
            classProduct: "chair" ,
            img: "29.png" ,
            },
            {
            id: "29" ,
            price: "9000" ,
            product: "Стул" ,
            classProduct: "chair" ,
            img: "30.png" ,
            },
            {
            id: "30" ,
            price: "11000" ,
            product: "Стол" ,
            classProduct: "table" ,
            img: "11.png" ,
            },
            {
            id: "31" ,
            price: "12000" ,
            product: "Стул" ,
            classProduct: "chair" ,
            img: "31.png" ,
            },
            {
            id: "32" ,
            price: "5000" ,
            product: "Стол" ,
            classProduct: "table" ,
            img: "12.png" ,
            },
            {
            id: "33" ,
            price: "4000" ,
            product: "Стул" ,
            classProduct: "chair" ,
            img: "32.png" ,
            },
            {
            id: "34" ,
            price: "9000" ,
            product: "Комплект" ,
            classProduct: "set" ,
            img: "44.png" ,
            },
            {
            id: "35" ,
            price: "3000" ,
            product: "Стол" ,
            classProduct: "table" ,
            img: "13.png" ,
            },
            {
            id: "36" ,
            price: "2000" ,
            product: "Стул" ,
            classProduct: "chair" ,
            img: "33.png" ,
            },
            {
            id: "37" ,
            price: "6000" ,
            product: "Стул" ,
            classProduct: "chair" ,
            img: "34.png" ,
            },
            {
            id: "38" ,
            price: "8000" ,
            product: "Стол" ,
            classProduct: "table" ,
            img: "14.png" ,
            },
            {
            id: "39" ,
            price: "10000" ,
            product: "Стул" ,
            classProduct: "chair" ,
            img: "35.png" ,
            },
            {
            id: "40" ,
            price: "5000" ,
            product: "Стул" ,
            classProduct: "chair" ,
            img: "36.png" ,
            },
            {
            id: "41" ,
            price: "10000" ,
            product: "Комплект" ,
            classProduct: "set" ,
            img: "45.png" ,
            },
            {
            id: "42" ,
            price: "9000" ,
            product: "Комплект" ,
            classProduct: "set" ,
            img: "46.png" ,
            },
            {
            id: "43" ,
            price: "4000" ,
            product: "Стол" ,
            classProduct: "table" ,
            img: "15.png" ,
            },
            {
            id: "44" ,
            price: "12000" ,
            product: "Комплект" ,
            classProduct: "set" ,
            img: "47.png" ,
            },
            {
            id: "45" ,
            price: "10000" ,
            product: "Стул" ,
            classProduct: "chair" ,
            img: "37.png" ,
            },
            {
            id: "46" ,
            price: "10000" ,
            product: "Стол" ,
            classProduct: "table" ,
            img: "16.png" ,
            },
            {
            id: "47" ,
            price: "9000" ,
            product: "Комплект" ,
            classProduct: "set" ,
            img: "48.png" ,
            },
            {
            id: "48" ,
            price: "12000" ,
            product: "Стол" ,
            classProduct: "table" ,
            img: "17.png" ,
            },
            {
            id: "49" ,
            price: "10000" ,
            product: "Стул" ,
            classProduct: "chair" ,
            img: "38.png" ,
            },
            {
            id: "50" ,
            price: "5000" ,
            product: "Комплект" ,
            classProduct: "set" ,
            img: "49.png" ,
            },
       
        ];  
    
